[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm prisma generate && pnpm build"

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[environment]
PORT = "3001"
